travelapplication/src/main/java/edu/chl/majc/travelapplication/DB/JPAFlightController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.chl.majc.travelapplication.DB;

import edu.chl.majc.travelapplication.core.Flight;
import edu.chl.majc.travelapplication.core.Flight_;
import java.io.Serializable;
import java.util.List;
import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import javax.persistence.PersistenceContext;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Path;
import javax.persistence.criteria.Root;

/**
 *
 * @author lujoel
 */
@Stateless
public class JPAFlightController implements Serializable{ 
    
    @PersistenceContext(unitName= "travel_pu" )
    private EntityManager em;

    public JPAFlightController() {
    }

    public void create(Flight entity) {
        em.persist(entity);
    }

    public void edit(Flight entity) {
        em.merge(entity);
    }

    public void remove(Flight entity) {
        em.remove(em.merge(entity));
    }

    public Flight find(String id) {
        return em.find(Flight.class, id);
    }

    public List<Flight> findAll() {
        javax.persistence.criteria.CriteriaQuery cq = em.getCriteriaBuilder().createQuery();
        cq.select(cq.from(Flight.class));
        return em.createQuery(cq).getResultList();
    }

    public List<Flight> findRange(int[] range) {
        javax.persistence.criteria.CriteriaQuery cq = em.getCriteriaBuilder().createQuery();
        cq.select(cq.from(Flight.class));
        javax.persistence.Query q = em.createQuery(cq);
        q.setMaxResults(range[1] - range[0]);
        q.setFirstResult(range[0]);
        return q.getResultList();
    }

    public int count() {
        javax.persistence.criteria.CriteriaQuery cq = em.getCriteriaBuilder().createQuery();
        javax.persistence.criteria.Root<Flight> rt = cq.from(Flight.class);
        cq.select(em.getCriteriaBuilder().count(rt));
        javax.persistence.Query q = em.createQuery(cq);
        return ((Long) q.getSingleResult()).intValue();
    }
    
    public List<String> getDestinations(){
        CriteriaQuery cq = em.getCriteriaBuilder().createQuery();
        Root<Flight> flight = cq.from(Flight.class);
        Path<String> destination = flight.get(Flight_.toAirport);
        cq.select(destination).distinct(true);
        return em.createQuery(cq).getResultList();
    }    
}

travelapplication/src/main/java/edu/chl/majc/travelapplication/OrderUtilityBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.chl.majc.travelapplication;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;

/**
 *
 * @author branting
 */
@ManagedBean(name="orderUtilityBean")
@RequestScoped
public class OrderUtilityBean {

    // Fields
    @ManagedProperty(value = "#{orderBackingBean}")
    OrderBackingBean obb;
    @ManagedProperty(value = "#{hotelBackingBean}")
    HotelBackingBean hbb;
    
    // Methods
    public String getCalculateTotalHotelPrice(){
        double total;
        
        // Should be calculated based on outbound and return dates of flight
        int nrOfDays = 7;
        
        if (hbb.getRoomtype().equalsIgnoreCase("double")){
            total = nrOfDays * obb.getBookedHotel().getDoubleroomPrice();
            return "" + total;
        } else {
            total = nrOfDays * obb.getBookedHotel().getSingleroomPrice();
            return "" + total;
        }
    }
    
    public int getCalculateNrOfNights(){
        //TODO
        return 0;
                
    }

    public HotelBackingBean getHbb() {
        return hbb;
    }

    public void setHbb(HotelBackingBean hbb) {
        this.hbb = hbb;
    }

    public OrderBackingBean getObb() {
        return obb;
    }

    public void setObb(OrderBackingBean obb) {
        this.obb = obb;
    }
    
    /** Creates a new instance of orderUtilityBean */
    public OrderUtilityBean() {
    }
    
    
}

travelapplication/src/main/webapp/WEB-INF/createCustomer.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:insert name="ff">
              <ui:include src="customerForm.xhtml" />
        </ui:insert>
    </h:body>
</html>

travelapplication/src/main/webapp/WEB-INF/customerForm.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:ice="http://www.icesoft.com/icefaces/component">
    <ice:form>
        <ice:panelGrid columns="3">
            <ice:outputLabel for="name" value="Name:" />
            <ice:inputText id="name" value="#{customerBackingBean.name}" validator="#{customerBackingBean.validateName}"/>
            <ice:message id="nameError" for="name"/>
            <ice:outputLabel for="password" value="Password:" />
            <ice:inputSecret id="password" value="#{customerBackingBean.password}" validator="#{customerBackingBean.validatePassword}"/>
            <ice:message id="passwordError" for="password"/>
            <ice:outputLabel for="address" value="Address:" />
            <ice:inputTextarea id="address" value="#{customerBackingBean.address}" validator="#{customerBackingBean.validateAddress}"/>
            <ice:message id="addressError" for="address"/>
            <ice:outputLabel for="email" value="Email:" />
            <ice:inputText id="email" value="#{customerBackingBean.email}" validator="#{customerBackingBean.validateEmail}"/>
            <ice:message id="emailError" for="email"/>
            <ice:commandButton value="Submit" actionListener="#{customerControllerBean.createCustomer}" />
        </ice:panelGrid>
    </ice:form>
    <ice:form>
        <ice:commandButton value="Cancel" actionListener="#{customerControllerBean.cancelRegistration}" />
    </ice:form>
</ui:composition>

travelapplication/src/main/webapp/WEB-INF/flightBooking.xhtml
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ice="http://www.icesoft.com/icefaces/component"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets"> 
    <div class="componentBox">
    <ice:form >
        <ice:outputText value="Choose destination:" />
        <ice:selectOneMenu value="#{orderBackingBean.selectedDestination}">
            <f:selectItems value="#{orderBackingBean.destinations}"/>
        </ice:selectOneMenu>
        <ice:selectInputDate value="#{orderBackingBean.date}" renderAsPopup="true" />
        <ice:commandButton value="Search" actionListener="#{orderControllerBean.showFlights}"/>
    </ice:form>
    </div>
</ui:composition>

travelapplication/src/main/webapp/WEB-INF/flightTable.xhtml
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ice="http://www.icesoft.com/icefaces/component"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets">

    <ice:form rendered="#{orderBackingBean.renderFlights}">
        <ice:outputText value="Availibe flights:" /> 
        <div class="componentBox">
            <ice:dataTable value="#{orderBackingBean.flights}" var="flight" width="100%">
                <ice:column style="text-align: center">
                    <f:facet name="header">
                        <ice:outputText value="Flight ID"/>
                    </f:facet>
                    <ice:outputText value="#{flight.flightId}"/>
                </ice:column>
                <ice:column style="text-align: center">
                    <f:facet name="header">
                        <ice:outputText value="Departure"/>
                    </f:facet>
                    <ice:outputText value="#{flight.fromAirport} #{flight.depTime}"/>
                </ice:column>
                <ice:column style="text-align: center">
                    <f:facet name="header">
                        <ice:outputText value="Arrival"/>
                    </f:facet>
                    <ice:outputText value="#{flight.toAirport} #{flight.arrTime}"/>
                </ice:column>
                <ice:column style="text-align: center">
                    <f:facet name="header">
                        <ice:outputText value="Price"/>
                    </f:facet>
                    <ice:outputText value="#{flight.price}"/>
                </ice:column>
                <ice:column style="text-align: center">
                    <f:facet name="header">
                        <ice:outputText value="Price"/>
                    </f:facet>
                    <ice:commandButton partialSubmit="true" value="Boka flyg" actionListener="#{orderControllerBean.chooseFlight}">
                        <f:attribute name="flight" value="#{flight}" />
                    </ice:commandButton>
                </ice:column>
            </ice:dataTable>
        </div>
    </ice:form>

</ui:composition>

travelapplication/src/main/webapp/WEB-INF/hotelBooking.xhtml
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ice="http://www.icesoft.com/icefaces/component"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets">
    
    
</ui:composition>

travelapplication/src/main/webapp/WEB-INF/hotelTable.xhtml
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ice="http://www.icesoft.com/icefaces/component"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets">

    <ice:form rendered="#{hotelBackingBean.renderHotels}">
        <ice:outputText value="Available hotels for your destination:" />
        <div class="componentBox">
            <ice:panelSeries var="hotelItem" value="#{hotelBackingBean.hotels}">
            <ice:panelGrid columns="2" >
                <ice:column>
                    <h:graphicImage url="#{hotelItem.imgURI}" width="200" />
                </ice:column>
                <ice:column>
                    <ice:outputLabel value="#{hotelItem.name}" /><br />
                    <ice:panelGrid columns="2">
                        <ice:outputText value="Price/double:" />
                        <ice:outputText value="#{hotelItem.doubleroomPrice}" />
                        <ice:outputText value="Price/single:" />
                        <ice:outputText value="#{hotelItem.singleroomPrice}" />
                        <ice:outputText value="Roomtype:"/>
                        <ice:selectOneRadio value="#{hotelBackingBean.roomtype}" >
                            <f:selectItem itemLabel="Double" itemValue="double" />
                            <f:selectItem itemLabel="Single" itemValue="single"/>
                        </ice:selectOneRadio>
                        <ice:outputText value="Description:" />
                        <ice:outputText value="#{hotelItem.description}" />
                    </ice:panelGrid>
                    <ice:commandButton value="Book" actionListener="#{orderControllerBean.selectHotel}">
                        <f:attribute name="Selected hotel" value="#{hotelItem}"/>
                    </ice:commandButton>
                </ice:column>
            </ice:panelGrid>
        </ice:panelSeries>
        </div>
    </ice:form>
</ui:composition>

travelapplication/src/main/webapp/WEB-INF/login.xhtml
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ice="http://www.icesoft.com/icefaces/component"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets">  
            
    <div class="sidePanelComponents">
        <ice:outputStyle href="/css/style.css" />
        <ice:outputText value="#{customerBackingBean.loginStatus}" />
        <ice:form>
            <ice:commandLink value="logout" rendered="#{!customerBackingBean.showLogin}" actionListener="#{customerControllerBean.logout}" />
        </ice:form>
        <ice:form rendered="#{customerBackingBean.showLogin}">
            <ice:panelGrid columns="2">
                <ice:outputLabel for="name" value="Email:" />
                <ice:inputText id="email" value="#{customerBackingBean.email}" required="true" size="12" />
                <ice:outputLabel for="password" value="Password:" />
                <ice:inputSecret id="password"  value="#{customerBackingBean.password}" required="true" size="12" />
                <ice:commandButton value="Login" actionListener="#{customerControllerBean.login}" />            
            </ice:panelGrid>
        </ice:form>
        <ice:form>
            <ice:commandLink value="Register" rendered="#{customerBackingBean.showLogin}" actionListener="#{customerControllerBean.showRegisterDialog}" />
            <ice:commandLink value="Show orders" rendered="#{!customerBackingBean.showLogin}" actionListener="#{customerControllerBean.showOrdersDialog}" />
        </ice:form>

    </div>
</ui:composition>

travelapplication/src/main/webapp/WEB-INF/orderDialog.xhtml
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ice="http://www.icesoft.com/icefaces/component"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets">            
    <ice:panelPopup modal="true" autoCentre="true" rendered="#{customerBackingBean.showOrderDialog}">
            <f:facet name="header">
                <ice:outputText value="Register" />
            </f:facet>
            <f:facet name="body">
                <ice:outputText value="BAJS"/>
            </f:facet>          
        </ice:panelPopup>
</ui:composition>

travelapplication/src/main/webapp/WEB-INF/orderPanel.xhtml
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ice="http://www.icesoft.com/icefaces/component"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets">

    <div class="sidePanelComponents">
        <ice:outputStyle href="/css/style.css" />

        <ice:form rendered="#{orderBackingBean.flightBooked}">
            <ice:panelGroup rendered="#{orderBackingBean.flightBooked}">
                <ice:outputLabel value="Flight"/>
                <ice:panelGrid columns="1" >
                    <ice:outputLabel value="Outbound"/>
                    <ice:outputText value="From: #{orderBackingBean.bookedFlight.fromAirport}"/>
                    <ice:outputText value="To: #{orderBackingBean.bookedFlight.toAirport}" />
                    <ice:outputText value="Dept time: #{orderBackingBean.bookedFlight.depTime}"/>
                    <ice:outputText value="Arr time: #{orderBackingBean.bookedFlight.arrTime}" />
                    <ice:outputText value="1 adult" />
                    <ice:outputText value="Price: #{orderBackingBean.bookedFlight.price}"/>
                </ice:panelGrid>
            </ice:panelGroup>
            <br/>
            <ice:panelGroup rendered="#{orderBackingBean.hotelBooked}">
                <ice:outputLabel value="Hotel"/>
                <ice:panelGrid columns="1" >
                    <ice:outputText value="Name: #{orderBackingBean.bookedHotel.name}"/>
                    <ice:outputText value="Closest city: #{orderBackingBean.bookedHotel.closestCity}" />
                    <ice:outputText value="Roomtype: #{hotelBackingBean.roomtype}" />
                    <ice:outputText value="# of nights: 7"/>
                    
                    <ice:outputText value="Price: #{orderUtilityBean.calculateTotalHotelPrice}"/>
                </ice:panelGrid>
            </ice:panelGroup>

            <ice:commandButton value="Checkout" actionListener="#{orderControllerBean}"/>
        </ice:form>
    </div>
</ui:composition>

travelapplication/src/main/webapp/WEB-INF/registerDialog.xhtml
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ice="http://www.icesoft.com/icefaces/component"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets">            
        <ice:panelPopup modal="true" autoCentre="true" rendered="#{customerBackingBean.showRegisterDialog}">
            <f:facet name="header">
                <ice:outputText value="Register" />
            </f:facet>
            <f:facet name="body">
                <ui:include src="customerForm.xhtml" />
            </f:facet>          
        </ice:panelPopup>
</ui:composition>